language: python
python:
  - "2.7.18"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
# command to install dependencies
install:
  - pip install -r requirements/test.txt
# command to run tests
script: python setup.py lint test 
after_success:
  - coveralls
